spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cfr
    username: ENC(pVFh/sHs7RgvCGOlcSl3Fg==)
    #root ENC(pVFh/sHs7RgvCGOlcSl3Fg==)
    #test ENC(mrcBUlx9hUxwVNVNS8ErZA==)
    password: ENC(ozJxEfavs5sEteOUmP6nGw==)

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp


server:
  error:
    whitelabel:
      enabled: false

jasypt:
  encryptor:
#    password:
    bean: jasyptStringEncryptor
#    property:
#      prefix: ENC(
#      suffix: )
#    algorithm: PBEWithMD5ANdDES
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator

#server:
#  port: 8080

open_api:
  naver:
    X_Naver_Client_Id: ENC(9B97xVDdud3c+pssOR1cnaHWI3t8H8VqnENMvX3ogrQ=)
    X_Naver_Client_Secret: ENC(aaKTEF/urPtJ/4NYLpHD0v3NHE4FiC6T)

#logging:
#  level:
#    org:
#      apache:
#        coyote:
#          http11: debug
