spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cfr
    #jdbc:mysql://cfrboard.cfxnvsonnizs.ap-northeast-2.rds.amazonaws.com/cfr
    #jdbc:mysql://localhost:3306/cfr
    username: ENC(pVFh/sHs7RgvCGOlcSl3Fg==)
    #root ENC(pVFh/sHs7RgvCGOlcSl3Fg==)
    #test ENC(mrcBUlx9hUxwVNVNS8ErZA==)
    password: ENC(ozJxEfavs5sEteOUmP6nGw==)
    #ENC(KXS8n60cPBlbL6bqjsJUWV6Q4z4tojuv)
    #ENC(ozJxEfavs5sEteOUmP6nGw==)

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp


server:
  error:
    whitelabel:
      enabled: false

jasypt:
  encryptor:
    password: 2d10fb44af7c
    bean: jasyptStringEncryptor
#    property:
#      prefix: ENC(
#      suffix: )
#    algorithm: PBEWithMD5ANdDES
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator

#server:
#  port: 8080

open_api:
  naver:
    X_Naver_Client_Id: ENC(9B97xVDdud3c+pssOR1cnaHWI3t8H8VqnENMvX3ogrQ=)
    X_Naver_Client_Secret: ENC(aaKTEF/urPtJ/4NYLpHD0v3NHE4FiC6T)

#logging:
#  level:
#    org:
#      apache:
#        coyote:
#          http11: debug

jwt:
  header: Authorization
  secret: and0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdp
  tokenValidityInMilliseconds: 36000000